name: iceedgepaper
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - asn1crypto=0.24.0
  - backcall=0.1.0
  - basemap=1.1.0
  - basemap-data-hires=1.2.0
  - blas=1.1
  - bleach=2.1.3
  - bokeh=0.12.16
  - bottleneck=1.2.1
  - ca-certificates=2019.3.9
  - cairo=1.14.10
  - cairocffi=0.7.2
  - cairosvg=2.1.3
  - cartopy=0.16.0
  - certifi=2019.3.9
  - cffi=1.11.5
  - cftime=1.0.0
  - chardet=3.0.4
  - click=6.7
  - cloudpickle=0.5.3
  - colorcet=1.0.0
  - cryptography=2.2.1
  - cssselect2=0.2.1
  - curl=7.60.0
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=0.17.5
  - dask-core=0.17.5
  - datashader=0.6.6
  - datashape=0.5.4
  - decorator=4.3.0
  - defusedxml=0.5.0
  - distributed=1.21.8
  - entrypoints=0.2.3
  - fontconfig=2.12.6
  - freetype=2.8.1
  - geos=3.6.2
  - gettext=0.19.8.1
  - glib=2.55.0
  - gsw=3.2.1
  - h5netcdf=0.6.1
  - h5py=2.8.0
  - hdf4=4.2.13
  - hdf5=1.10.1
  - heapdict=1.0.0
  - holoviews=1.10.5
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.6
  - imageio=2.3.0
  - ipykernel=4.8.2
  - ipython=6.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.1
  - jedi=0.12.0
  - jinja2=2.10
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.0
  - jupyter_core=4.4.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.0
  - jupyterlab=0.35.4
  - jupyterlab_launcher=0.10.5
  - jupyterlab_server=0.2.0
  - kiwisolver=1.0.1
  - krb5=1.14.6
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libiconv=1.15
  - libnetcdf=4.6.1
  - libpng=1.6.34
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxml2=2.9.8
  - libxslt=1.1.32
  - llvmlite=0.23.0
  - locket=0.2.0
  - lxml=4.2.1
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mistune=0.8.3
  - msgpack-python=0.5.6
  - multipledispatch=0.5.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - netcdf4=1.4.0
  - networkx=2.1
  - notebook=5.5.0
  - numba=0.38.1
  - numpy=1.14.4
  - olefile=0.45.1
  - openblas=0.2.20
  - openssl=1.0.2r
  - owslib=0.16.0
  - packaging=17.1
  - pandas=0.23.4
  - pandoc=2.2.1
  - pandocfilters=1.4.2
  - param=1.6.1
  - parso=0.2.1
  - partd=0.3.8
  - patsy=0.5.0
  - pcre=8.41
  - pexpect=4.6.0
  - phantomjs=2.1.1
  - pickleshare=0.7.4
  - pillow=5.1.0
  - pip=10.0.1
  - pixman=0.34.0
  - proj4=4.9.3
  - prompt_toolkit=1.0.15
  - psutil=5.4.6
  - ptyprocess=0.5.2
  - pycparser=2.18
  - pyct=0.4.3
  - pyepsg=0.3.2
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyproj=1.9.5.1
  - pyqt=5.6.0
  - pyshp=1.2.12
  - pysocks=1.6.8
  - pysolar=0.8
  - python=3.6.5
  - python-dateutil=2.7.3
  - pytz=2018.4
  - pyviz_comms=0.1.1
  - pywavelets=0.5.2
  - pyyaml=3.12
  - pyzmq=17.0.0
  - qt=5.6.2
  - qtconsole=4.3.1
  - readline=7.0
  - requests=2.18.4
  - scikit-image=0.14.0
  - scipy=1.1.0
  - seaborn=0.8.1
  - selenium=3.12.0
  - send2trash=1.5.0
  - setuptools=39.2.0
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - sip=4.18
  - six=1.11.0
  - sortedcontainers=2.0.3
  - sqlite=3.23.1
  - statsmodels=0.9.0
  - tblib=1.3.2
  - terminado=0.8.1
  - testpath=0.3.1
  - tinycss2=0.6.1
  - tk=8.6.7
  - toolz=0.9.0
  - tornado=5.0.2
  - traitlets=4.3.2
  - urllib3=1.22
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.31.1
  - widgetsnbextension=3.2.1
  - xarray=0.11.2
  - xlrd=1.1.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zict=0.1.3
  - zlib=1.2.11
  - pip:
    - bibtexparser==1.0.1
    - future==0.16.0
    - ipypublish==0.6.5
    - pathlib2==2.3.2
    - scikit-fuzzy==0.3.1
    - seabird==0.10.5
