name: iceedgepaper
channels:
  - conda-forge
dependencies:
  - asn1crypto
  - backcall
  - basemap
  - basemap-data-hires
  - blas
  - bleach
  - bokeh
  - bottleneck
  - ca-certificates
  - cairo
  - cairocffi
  - cairosvg
  - cartopy
  - certifi
  - cffi
  - cftime
  - chardet
  - click
  - cloudpickle
  - colorcet
  - cryptography
  - cssselect2
  - curl
  - cycler
  - cytoolz
  - dask
  - dask-core
  - datashader
  - datashape
  - decorator
  - defusedxml
  - distributed
  - entrypoints
  - fontconfig
  - freetype
  - geos
  - gettext
  - glib
  - gsw
  - h5netcdf
  - h5py
  - hdf4
  - hdf5
  - heapdict
  - holoviews
  - html5lib
  - icu
  - idna
  - imageio
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_contrib_nbextensions
  - jupyter_core
  - jupyter_highlight_selected_word
  - jupyter_latex_envs
  - jupyter_nbextensions_configurator
  - jupyterlab
  - jupyterlab_launcher
  - jupyterlab_server
  - kiwisolver
  - krb5
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libgfortran
  - libiconv
  - libnetcdf
  - libpng
  - libsodium
  - libssh2
  - libtiff
  - libxml2
  - libxslt
  - llvmlite
  - locket
  - lxml
  - markupsafe
  - matplotlib
  - mistune
  - msgpack-python
  - multipledispatch
  - nbconvert
  - nbformat
  - ncurses
  - netcdf4
  - networkx
  - notebook
  - numba
  - numpy
  - olefile
  - openblas
  - openssl
  - owslib
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - param
  - parso
  - partd
  - patsy
  - pcre
  - pexpect
  - phantomjs
  - pickleshare
  - pillow
  - pip
  - pixman
  - proj4
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pycparser
  - pyct
  - pyepsg
  - pygments
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyshp
  - pysocks
  - pysolar
  - python
  - python-dateutil
  - pytz
  - pyviz_comms
  - pywavelets
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - readline
  - requests
  - scikit-image
  - scipy
  - seaborn
  - selenium
  - send2trash
  - setuptools
  - shapely
  - simplegeneric
  - sip
  - six
  - sortedcontainers
  - sqlite
  - statsmodels
  - tblib
  - terminado
  - testpath
  - tinycss2
  - tk
  - toolz
  - tornado
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - wheel
  - widgetsnbextension
  - xarray
  - xlrd
  - xz
  - yaml
  - zeromq
  - zict
  - zlib
  - pip:
    - bibtexparser
    - future
    - pathlib2
    - scikit-fuzzy
    - seabird
